# Generated by Django 3.2 on 2021-04-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Unique id for user')),
                ('email', models.EmailField(max_length=254, verbose_name='User email')),
                ('password', models.TextField(verbose_name='User password')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
