# Generated by Django 3.2 on 2021-04-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uix', '0004_alter_user_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
