# Generated by Django 3.2 on 2021-05-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('author', models.TextField()),
                ('description', models.TextField()),
                ('img_link', models.URLField()),
                ('link', models.URLField()),
                ('download_link', models.URLField()),
            ],
        ),
    ]
