# Generated by Django 3.2 on 2021-05-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_books', '0002_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(verbose_name='Author of book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Description of book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='download_link',
            field=models.URLField(verbose_name='Link to download book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='img_link',
            field=models.URLField(verbose_name='Link of book cover'),
        ),
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(unique=True, verbose_name='Link to book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.TextField(verbose_name='Title of book'),
        ),
    ]
